# Generated by Django 6.0.5 on 2026-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://www.shutterstock.com/image-photo/petty-burger-isolated-on-transparent-260nw-2614206767.jpg', max_length=400)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('vegeterian', models.BooleanField(default=False)),
            ],
        ),
    ]
