# Generated by Django 6.0.5 on 2026-05-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vegeterian',
            new_name='vegetarian',
        ),
    ]
